[package]
name = "sparkles"
description = "Capture execution flow of your Rust application with CPU cycle precision!"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/skibon02/sparkles"
readme = "../README.md"

[dependencies]
sparkles-core = {version = "0.2.0", path = "../sparkles-core"}
sparkles-macro = {version = "0.2.0", path = "../sparkles-macro", features = ["included-from-sparkles"]}
bincode = "2.0.1"
log = { version = "0.4.27", default-features = false }
ringbuf = "0.4.8"
thread-id = { version = "5.0.0" }
chrono = "0.4.41"
parking_lot = "0.12.4"
multicast-discovery-socket = { version = "0.1.2", optional = true }
smallvec = "1.15.1"

# Linux/Android: libc for clock_gettime
[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
libc = "0.2.175"

# Windows: winapi for QueryPerformanceCounter
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["profileapi", "ntdef"] }

[dev-dependencies]
# for examples
simple_logger = "5.0.0"
clap = { version = "4.5.40", features = ["derive"] }
# for puffin tests
puffin_http = "0.16.1"
puffin = { version = "0.19.1" }


[features]
default = ["self-tracing", "udp-streaming"]
udp-streaming = ["dep:multicast-discovery-socket"]
accurate-timestamps-x86 = ["sparkles-core/accurate-timestamps-x86"]
self-tracing = ["sparkles-core/self-tracing"]
unstable-thread-id = []
force-fallback-impl = ["sparkles-core/force-fallback-impl"]
